### PR TITLE
implement fts3 client

### PR DESCRIPTION
**Pull request by alberto-sanchez**
Implementation of fts3 clients. We have used fts3-clients, which should be available in each site, just like previous clients. This client is "rest" enable and should be able useful for future additions to phedex. service should be pointing to "rest" port (8446).
Do not merge yet!.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
as it. the implementation has been fully tested in lifecycle and in a real site setup. either with plain input or json. This can be merge!.

**Comment by nikmagini** [comment]
Hi Alberto,

many thanks, this looks good!
Just one comment: I think that the proper priority command in the fts3 client is 'fts-set-priority' (note additional dash), could you please fix that?

Thanks!
Nicolo'

**Comment by alberto-sanchez** [comment]
Hi Nicolo,
   Done!. sorry for that. That command was never tested again the real server, and in the lifecycle just does no do anything. I have fixed that.

Alberto

**Comment by nikmagini** [comment]
Hi Alberto,

thanks! One last comment: maybe it's better to set default --use-json to yes instead of no; this format is better for possible future extension to new FTS3 features (like multi-hop or multi-source)

Cheers
N.

**Comment by alberto-sanchez** [comment]
done!.

**Pull request merged**
