### PR TITLE
Addressing issue #1085

### PR DESCRIPTION
**Pull request by alberto-sanchez**
This should address the basic requirements of issue #1085

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
I have fts-client 3.6.8, the one it comes from osg stack. and it works

 fts-transfer-submit --version
client_version : 3.6.8

In cmslpc36.fnal.gov, also works
fts-transfer-submit --version
client_version : 3.2.32

it must be something about your client.  The parsing works fine, was fixed in client version 3.5.1, see
https://its.cern.ch/jira/browse/FTS-648

**Comment by nataliaratnikova** [comment]
It's good that 3.6.8 works . Unfortunately 3.5.7 at the moment is the default version  on lxpus.cern.ch and  the one that is used at many sites.

**Comment by alberto-sanchez** [comment]
I already have patch that. I just waiting for some test to run, because I fixing some typos as well

**Comment by nataliaratnikova** [comment]
Ready for the new release candidate https://github.com/dmwm/PHEDEX/issues/1082
as dicsussed

**Pull request merged**
